CREATE TYPE [dbo].[PullRequestTableType] AS TABLE (
  [Id]                  BIGINT         NULL,
  [UserId]              BIGINT         NOT NULL,
  [Number]              INT            NOT NULL,
  [State]               NVARCHAR(6)    NOT NULL,
  [Title]               NVARCHAR(MAX)  NOT NULL,
  [Body]                NVARCHAR(MAX)  NULL,
  [MilestoneId]         BIGINT         NULL,
  [Locked]              BIT            NOT NULL,
  [CreatedAt]           DATETIMEOFFSET NOT NULL,
  [UpdatedAt]           DATETIMEOFFSET NOT NULL,
  [ClosedAt]            DATETIMEOFFSET NULL,
  [ClosedById]          BIGINT         NULL,
  [PullRequest]         BIT            NOT NULL,
  [Reactions]           NVARCHAR(MAX)  NULL,
  [PullRequestId]       BIGINT         NOT NULL PRIMARY KEY CLUSTERED,
  [MaintainerCanModify] BIT            NOT NULL,
  [Mergeable]           BIT            NOT NULL,
  [MergeCommitSha]      NVARCHAR(500)  NULL,
  [Merged]              BIT            NOT NULL,
  [MergedAt]            DATETIMEOFFSET NULL,
  [MergedById]          BIGINT         NULL,
  [BaseJson]            NVARCHAR(MAX)  NOT NULL,
  [HeadJson]            NVARCHAR(MAX)  NOT NULL
)
