#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealArtists.ShipHub.Mail.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Views\CardExpiryReminderHtml.cshtml"
    using RealArtists.ShipHub.Mail;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\CardExpiryReminderHtml.cshtml"
    using RealArtists.ShipHub.Mail.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class CardExpiryReminderHtml : ShipHubTemplateBase<CardExpiryReminderMailMessage>
    {
#line hidden
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\CardExpiryReminderHtml.cshtml"
  
  Layout = new RealArtists.ShipHub.Mail.Views.LayoutHtml() { Model = Model };

            
            #line default
            #line hidden
WriteLiteral("\r\n<p>\r\n    Your credit card ending in <strong>");

            
            #line 9 "..\..\Views\CardExpiryReminderHtml.cshtml"
                                  Write(Model.LastCardDigits);

            
            #line default
            #line hidden
WriteLiteral("</strong> ");

            
            #line 9 "..\..\Views\CardExpiryReminderHtml.cshtml"
                                                                  Write(Model.AlreadyExpired ? "expired on" : "will expire on");

            
            #line default
            #line hidden
WriteLiteral(" <strong>");

            
            #line 9 "..\..\Views\CardExpiryReminderHtml.cshtml"
                                                                                                                                   Write(Model.ExpiryMonth);

            
            #line default
            #line hidden
WriteLiteral("/");

            
            #line 9 "..\..\Views\CardExpiryReminderHtml.cshtml"
                                                                                                                                                      Write(Model.ExpiryYear);

            
            #line default
            #line hidden
WriteLiteral("</strong>.\r\n</p>\r\n<p>\r\n    To prevent any interuption in your Ship service, pleas" +
"e update your payment information using the link below.\r\n</p>\r\n<p");

WriteLiteral(" class=\"last\"");

WriteLiteral(">\r\n    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 621), Tuple.Create("\"", 657)
            
            #line 15 "..\..\Views\CardExpiryReminderHtml.cshtml"
, Tuple.Create(Tuple.Create("", 628), Tuple.Create<System.Object, System.Int32>(Model.UpdatePaymentMethodUrl
            
            #line default
            #line hidden
, 628), false)
);

WriteLiteral(">Update Payment Information</a>\r\n</p>\r\n");

        }
    }
}
#pragma warning restore 1591
