#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealArtists.ShipHub.Mail.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Views\CardExpiryReminderPlain.cshtml"
    using RealArtists.ShipHub.Mail;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\CardExpiryReminderPlain.cshtml"
    using RealArtists.ShipHub.Mail.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class CardExpiryReminderPlain : ShipHubTemplateBase<CardExpiryReminderMailMessage>
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");





            
            #line 5 "..\..\Views\CardExpiryReminderPlain.cshtml"
  
  Layout = new RealArtists.ShipHub.Mail.Views.LayoutPlain() { Model = Model };


            
            #line default
            #line hidden
WriteLiteral("Your credit card ending in \"");


            
            #line 8 "..\..\Views\CardExpiryReminderPlain.cshtml"
                       Write(Model.LastCardDigits);

            
            #line default
            #line hidden
WriteLiteral("\" ");


            
            #line 8 "..\..\Views\CardExpiryReminderPlain.cshtml"
                                               Write(Model.AlreadyExpired ? "expired on" : "will expire on");

            
            #line default
            #line hidden
WriteLiteral(" \"");


            
            #line 8 "..\..\Views\CardExpiryReminderPlain.cshtml"
                                                                                                         Write(Model.ExpiryMonth);

            
            #line default
            #line hidden
WriteLiteral("/");


            
            #line 8 "..\..\Views\CardExpiryReminderPlain.cshtml"
                                                                                                                            Write(Model.ExpiryYear);

            
            #line default
            #line hidden
WriteLiteral("\".\r\n\r\nTo prevent any interuption in your Ship service, please update your payment" +
" information using the link below.\r\n\r\nLink: ");


            
            #line 12 "..\..\Views\CardExpiryReminderPlain.cshtml"
 Write(Model.UpdatePaymentMethodUrl);

            
            #line default
            #line hidden
WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
