#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealArtists.ShipHub.Mail.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class LayoutPlain : RealArtists.ShipHub.Mail.ShipHubTemplateBase<RealArtists.ShipHub.Mail.Models.MailMessageBase>
    {
#line hidden
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 3 "..\..\Views\LayoutPlain.cshtml"
 if (!SkipHeaderFooter) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral("Hi ");

            
            #line 3 "..\..\Views\LayoutPlain.cshtml"
                              Write(Model.FirstName);

            
            #line default
            #line hidden
WriteLiteral(",");

WriteLiteral(" ");

            
            #line 3 "..\..\Views\LayoutPlain.cshtml"
                                                            }

            
            #line default
            #line hidden
            
            #line 4 "..\..\Views\LayoutPlain.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\LayoutPlain.cshtml"
 if (!SkipHeaderFooter) {

            
            #line default
            #line hidden
WriteLiteral("Reply to this email if you have any questions - we\'re happy to help.\r\n\r\nReal Arti" +
"sts, Inc.\r\nsupport@realartists.com\r\n");

WriteLiteral("\r\n");

            
            #line 11 "..\..\Views\LayoutPlain.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
