#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealArtists.ShipHub.Mail.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Views\PaymentSucceededPersonalHtml.cshtml"
    using RealArtists.ShipHub.Mail;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\PaymentSucceededPersonalHtml.cshtml"
    using RealArtists.ShipHub.Mail.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class PaymentSucceededPersonalHtml : ShipHubTemplateBase<PaymentSucceededPersonalMailMessage>
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");





            
            #line 5 "..\..\Views\PaymentSucceededPersonalHtml.cshtml"
  
  Layout = new RealArtists.ShipHub.Mail.Views.LayoutHtml() { Model = Model };


            
            #line default
            #line hidden
WriteLiteral("<p>\r\n    We received payment for your personal Ship subscription.\r\n</p>\r\n<p>\r\n   " +
" <strong>");


            
            #line 12 "..\..\Views\PaymentSucceededPersonalHtml.cshtml"
       Write(string.Format("{0:C}", Model.AmountPaid));

            
            #line default
            #line hidden
WriteLiteral("</strong> was charged to your ");


            
            #line 12 "..\..\Views\PaymentSucceededPersonalHtml.cshtml"
                                                                              Write(PaymentMethodSummaryHtml(Model.PaymentMethodSummary));

            
            #line default
            #line hidden
WriteLiteral("\r\n    and covers service through <strong>");


            
            #line 13 "..\..\Views\PaymentSucceededPersonalHtml.cshtml"
                                  Write(Model.ServiceThroughDate.ToString("MMM d, yyyy"));

            
            #line default
            #line hidden
WriteLiteral("</strong>.\r\n</p>\r\n<p>\r\n    <a href=\"");


            
            #line 16 "..\..\Views\PaymentSucceededPersonalHtml.cshtml"
        Write(Model.InvoicePdfUrl);

            
            #line default
            #line hidden
WriteLiteral("\">Download a PDF receipt</a> for your records.\r\n</p>\r\n<p class=\"last\">\r\n    We ap" +
"preciate your business!\r\n</p>\r\n");


        }
    }
}
#pragma warning restore 1591
