#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealArtists.ShipHub.Mail.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
    using RealArtists.ShipHub.Mail;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
    using RealArtists.ShipHub.Mail.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class PaymentSucceededOrganizationHtml : ShipHubTemplateBase<PaymentSucceededOrganizationMailMessage>
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");





            
            #line 5 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
  
  Layout = new RealArtists.ShipHub.Mail.Views.LayoutHtml() { Model = Model };


            
            #line default
            #line hidden
WriteLiteral("<p>\r\n    We received payment for your organization Ship subscription.\r\n</p>\r\n<p>\r" +
"\n    <strong>");


            
            #line 12 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
       Write(string.Format("{0:C}", Model.AmountPaid));

            
            #line default
            #line hidden
WriteLiteral("</strong> was charged to your ");


            
            #line 12 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
                                                                              Write(PaymentMethodSummaryHtml(Model.PaymentMethodSummary));

            
            #line default
            #line hidden
WriteLiteral("\r\n    and covers service through <strong>");


            
            #line 13 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
                                  Write(Model.ServiceThroughDate.ToString("MMM d, yyyy"));

            
            #line default
            #line hidden
WriteLiteral("</strong>.\r\n</p>\r\n<p>\r\n    <a href=\"");


            
            #line 16 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
        Write(Model.InvoicePdfUrl);

            
            #line default
            #line hidden
WriteLiteral("\">Download a PDF receipt</a> for your records.\r\n</p>\r\n\r\n<p>\r\n    In the prior mon" +
"th beginning on ");


            
            #line 20 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
                               Write(Model.PreviousMonthStart.ToString("MMM d, yyyy"));

            
            #line default
            #line hidden
WriteLiteral(", your organization\r\n    had <strong>");


            
            #line 21 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
           Write(Model.PreviousMonthActiveUsersCount);

            
            #line default
            #line hidden
WriteLiteral(" active Ship user");


            
            #line 21 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
                                                                 Write(Model.PreviousMonthActiveUsersCount == 1 ? "" : "s");

            
            #line default
            #line hidden
WriteLiteral("</strong>.\r\n</p>\r\n");


            
            #line 23 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
 if (Model.PreviousMonthActiveUsersCount > 1) {

            
            #line default
            #line hidden
WriteLiteral("<p>\r\n    The base monthly fee (paid as part of your last invoice) covers the firs" +
"t active Ship user, so you were billed for ");


            
            #line 25 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
                                                                                                                   Write(Model.PreviousMonthActiveUsersCount - 1);

            
            #line default
            #line hidden
WriteLiteral("\r\n    additional active user");


            
            #line 26 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
                      Write((Model.PreviousMonthActiveUsersCount - 1) == 1 ? "" : "s");

            
            #line default
            #line hidden
WriteLiteral(" on this invoice.\r\n</p>\r\n");


            
            #line 28 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
}

            
            #line default
            #line hidden

            
            #line 29 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
 if (Model.PreviousMonthActiveUsersCount > 0) {
    if (Model.PreviousMonthActiveUsersCount == Model.PreviousMonthActiveUsersSample.Length) {

            
            #line default
            #line hidden
WriteLiteral("    <p>\r\n        Active Ship users in your organization in the prior month were: " +
"");


            
            #line 32 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
                                                                    Write(string.Join(", ", Model.PreviousMonthActiveUsersSample.Select(x => "<strong>" + x + "</strong>")));

            
            #line default
            #line hidden
WriteLiteral(".\r\n    </p>\r\n");


            
            #line 34 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
    } else {

            
            #line default
            #line hidden
WriteLiteral("    <p>\r\n        Active Ship users in your organization in the prior month includ" +
"ed: ");


            
            #line 36 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
                                                                        Write(string.Join(", ", Model.PreviousMonthActiveUsersSample.Select(x => "<strong>" + x + "</strong>")));

            
            #line default
            #line hidden
WriteLiteral(", and <strong>");


            
            #line 36 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
                                                                                                                                                                                          Write(Model.PreviousMonthActiveUsersCount - Model.PreviousMonthActiveUsersSample.Count());

            
            #line default
            #line hidden
WriteLiteral(" others</strong>.\r\n    </p>\r\n");


            
            #line 38 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
    }
}

            
            #line default
            #line hidden
WriteLiteral("<p class=\"last\">\r\n    We appreciate your business!\r\n</p>\r\n");


        }
    }
}
#pragma warning restore 1591
