#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealArtists.ShipHub.Mail.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Views\PaymentFailedPlain.cshtml"
    using RealArtists.ShipHub.Mail;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\PaymentFailedPlain.cshtml"
    using RealArtists.ShipHub.Mail.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class PaymentFailedPlain : ShipHubTemplateBase<PaymentFailedMailMessage>
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");





            
            #line 5 "..\..\Views\PaymentFailedPlain.cshtml"
  
  Layout = new RealArtists.ShipHub.Mail.Views.LayoutPlain() { Model = Model };


            
            #line default
            #line hidden
WriteLiteral("We tried to process a charge for ");


            
            #line 8 "..\..\Views\PaymentFailedPlain.cshtml"
                            Write(string.Format("{0:C}", Model.Amount));

            
            #line default
            #line hidden
WriteLiteral(" to your ");


            
            #line 8 "..\..\Views\PaymentFailedPlain.cshtml"
                                                                          Write(PaymentMethodSummaryPlain(Model.PaymentMethodSummary));

            
            #line default
            #line hidden
WriteLiteral(", but the transaction failed.\r\n\r\nReason: ");


            
            #line 10 "..\..\Views\PaymentFailedPlain.cshtml"
   Write(Model.ErrorText);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\nDownload a PDF invoice for this transaction:\r\n");


            
            #line 13 "..\..\Views\PaymentFailedPlain.cshtml"
Write(Model.InvoicePdfUrl);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 15 "..\..\Views\PaymentFailedPlain.cshtml"
 if (Model.NextRetryDate != null) {

            
            #line default
            #line hidden
WriteLiteral("We\'ll automatically retry this charge on ");


            
            #line 16 "..\..\Views\PaymentFailedPlain.cshtml"
                                           Write(Model.NextRetryDate.Value.ToString("MMM d, yyyy"));

            
            #line default
            #line hidden
WriteLiteral(".  If you need to update your payment information, follow the link below.\r\n\r\nLink" +
": ");


            
            #line 18 "..\..\Views\PaymentFailedPlain.cshtml"
 Write(Model.UpdatePaymentMethodUrl);

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 19 "..\..\Views\PaymentFailedPlain.cshtml"
} else {

            
            #line default
            #line hidden
WriteLiteral(@"We've failed to process this charge a few times now, so we'll go ahead and cancel your subscription.

If you want to re-activate your subscription later, you can do so from the Ship application.  From the ""Ship"" menu, choose ""Manage Subscription"".  Then click ""Buy"" for your account.");

WriteLiteral("\r\n");


            
            #line 23 "..\..\Views\PaymentFailedPlain.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
