#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealArtists.ShipHub.Mail.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
    using RealArtists.ShipHub.Mail;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
    using RealArtists.ShipHub.Mail.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class PaymentSucceededOrganizationHtml : ShipHubTemplateBase<PaymentSucceededOrganizationMailMessage>
    {
#line hidden
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
  
  Layout = new RealArtists.ShipHub.Mail.Views.LayoutHtml() { Model = Model };

            
            #line default
            #line hidden
WriteLiteral("\r\n<p>\r\n    We received payment for your organization Ship subscription.\r\n</p>\r\n<p" +
">\r\n    <strong>");

            
            #line 12 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
       Write(string.Format("{0:C}", Model.AmountPaid));

            
            #line default
            #line hidden
WriteLiteral("</strong> was charged to your card ending\r\n    in <strong>");

            
            #line 13 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
          Write(Model.LastCardDigits);

            
            #line default
            #line hidden
WriteLiteral("</strong> and covers service through <strong>");

            
            #line 13 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
                                                                            Write(Model.ServiceThroughDate.ToString("MMM d, yyyy"));

            
            #line default
            #line hidden
WriteLiteral("</strong>.\r\n    Attached is an invoice receipt for your records.\r\n</p>\r\n");

            
            #line 16 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
 if (Model.PreviousMonthActiveUsersCount <= 5) {

            
            #line default
            #line hidden
WriteLiteral("<p>\r\n    The base monthly fee of your subscription covers the first 5 active Ship" +
" users per month.  Your organization\r\n    had <strong>");

            
            #line 19 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
           Write(Model.PreviousMonthActiveUsersCount);

            
            #line default
            #line hidden
WriteLiteral(" active Ship users</strong> in the prior month beginning on\r\n");

WriteLiteral("    ");

            
            #line 20 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
Write(Model.PreviousMonthStart.ToString("MMM d, yyyy"));

            
            #line default
            #line hidden
WriteLiteral(", so there were no additional usage charges.\r\n</p>\r\n");

            
            #line 22 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
} else {

            
            #line default
            #line hidden
WriteLiteral("<p>\r\n    The base monthly fee of your subscription covers the first 5 active Ship" +
" users per month.  Your organization\r\n    had <strong>");

            
            #line 25 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
           Write(Model.PreviousMonthActiveUsersCount);

            
            #line default
            #line hidden
WriteLiteral(" active Ship users</strong> in the prior month beginning on\r\n");

WriteLiteral("    ");

            
            #line 26 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
Write(Model.PreviousMonthStart.ToString("MMM d, yyyy"));

            
            #line default
            #line hidden
WriteLiteral(", so you were billed for <strong>");

            
            #line 26 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
                                                                                  Write(Model.PreviousMonthActiveUsersCount - 5);

            
            #line default
            #line hidden
WriteLiteral(" additional active users.</strong>\r\n</p>\r\n");

            
            #line 28 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
}

            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
 if (Model.PreviousMonthActiveUsersCount == Model.PreviousMonthActiveUsersSample.Count()) {

            
            #line default
            #line hidden
WriteLiteral("<p>\r\n    Active Ship users in your organization in the prior month were ");

            
            #line 31 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
                                                               Write(string.Join(", ", Model.PreviousMonthActiveUsersSample.Select(x => "<strong>" + x + "</strong>")));

            
            #line default
            #line hidden
WriteLiteral(".\r\n</p>\r\n");

            
            #line 33 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
} else {

            
            #line default
            #line hidden
WriteLiteral("<p>\r\n    Active Ship users in your organization in the prior month included: ");

            
            #line 35 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
                                                                    Write(string.Join(", ", Model.PreviousMonthActiveUsersSample.Select(x => "<strong>" + x + "</strong>")));

            
            #line default
            #line hidden
WriteLiteral(", and <strong>");

            
            #line 35 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
                                                                                                                                                                                      Write(Model.PreviousMonthActiveUsersCount - Model.PreviousMonthActiveUsersSample.Count());

            
            #line default
            #line hidden
WriteLiteral(" others</strong>.\r\n</p>\r\n");

            
            #line 37 "..\..\Views\PaymentSucceededOrganizationHtml.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<p");

WriteLiteral(" class=\"last\"");

WriteLiteral(">\r\n    We appreciate your business!\r\n</p>\r\n");

        }
    }
}
#pragma warning restore 1591
