#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealArtists.ShipHub.Mail.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Views\PaymentFailedHtml.cshtml"
    using RealArtists.ShipHub.Mail;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\PaymentFailedHtml.cshtml"
    using RealArtists.ShipHub.Mail.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class PaymentFailedHtml : ShipHubTemplateBase<PaymentFailedMailMessage>
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");





            
            #line 5 "..\..\Views\PaymentFailedHtml.cshtml"
  
  Layout = new RealArtists.ShipHub.Mail.Views.LayoutHtml() { Model = Model };


            
            #line default
            #line hidden
WriteLiteral("<p>\r\n    We tried to process a charge for <strong>");


            
            #line 9 "..\..\Views\PaymentFailedHtml.cshtml"
                                        Write(string.Format("{0:C}", Model.Amount));

            
            #line default
            #line hidden
WriteLiteral("</strong> to your card ending\r\n    in <strong>");


            
            #line 10 "..\..\Views\PaymentFailedHtml.cshtml"
          Write(Model.LastCardDigits);

            
            #line default
            #line hidden
WriteLiteral("</strong>, but the transaction failed.\r\n</p>\r\n<p>\r\n    <strong>Reason:</strong> ");


            
            #line 13 "..\..\Views\PaymentFailedHtml.cshtml"
                        Write(Model.ErrorText);

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n<p>\r\n    <a href=\"");


            
            #line 16 "..\..\Views\PaymentFailedHtml.cshtml"
        Write(Model.InvoicePdfUrl);

            
            #line default
            #line hidden
WriteLiteral("\">Download a PDF invoice</a> for this transaction.\r\n</p>\r\n");


            
            #line 18 "..\..\Views\PaymentFailedHtml.cshtml"
 if (Model.NextRetryDate != null) {

            
            #line default
            #line hidden
WriteLiteral("    <p>\r\n        We\'ll automatically retry this charge on <strong>");


            
            #line 20 "..\..\Views\PaymentFailedHtml.cshtml"
                                                     Write(Model.NextRetryDate.Value.ToString("MMM d, yyyy"));

            
            #line default
            #line hidden
WriteLiteral("</strong>.\r\n        If you need to update your payment information, follow the li" +
"nk below.\r\n    </p>\r\n");



WriteLiteral("    <p class=\"last\">\r\n        <a href=\"");


            
            #line 24 "..\..\Views\PaymentFailedHtml.cshtml"
            Write(Model.UpdatePaymentMethodUrl);

            
            #line default
            #line hidden
WriteLiteral("\">Update Payment Information</a>\r\n    </p>\r\n");


            
            #line 26 "..\..\Views\PaymentFailedHtml.cshtml"
} else {

            
            #line default
            #line hidden
WriteLiteral("    <p>\r\n        We\'ve failed to process this charge a few times now, so we\'ll go" +
" ahead and cancel your subscription.\r\n    </p>\r\n");



WriteLiteral(@"    <p class=""last"">
        If you want to re-activate your subscription later, you can do so from the Ship application.  
        From the <em>Ship</em> menu, choose <em>Manage Subscription</em>.  Then click <em>Manage</em> for your account.
    </p>
");


            
            #line 34 "..\..\Views\PaymentFailedHtml.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
