#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealArtists.ShipHub.Mail.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Views\PaymentRefundedHtml.cshtml"
    using RealArtists.ShipHub.Mail;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\PaymentRefundedHtml.cshtml"
    using RealArtists.ShipHub.Mail.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class PaymentRefundedHtml : ShipHubTemplateBase<PaymentRefundedMailMessage>
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");





            
            #line 5 "..\..\Views\PaymentRefundedHtml.cshtml"
  
  Layout = new RealArtists.ShipHub.Mail.Views.LayoutHtml() { Model = Model };


            
            #line default
            #line hidden
WriteLiteral("<p>\r\n    We\'ve issued a refund for <strong>");


            
            #line 9 "..\..\Views\PaymentRefundedHtml.cshtml"
                                 Write(string.Format("{0:C}", Model.AmountRefunded));

            
            #line default
            #line hidden
WriteLiteral("</strong> to your card ending\r\n    in <strong>");


            
            #line 10 "..\..\Views\PaymentRefundedHtml.cshtml"
          Write(Model.LastCardDigits);

            
            #line default
            #line hidden
WriteLiteral("</strong>.\r\n</p>\r\n<p>\r\n    <a href=\"");


            
            #line 13 "..\..\Views\PaymentRefundedHtml.cshtml"
        Write(Model.CreditNotePdfUrl);

            
            #line default
            #line hidden
WriteLiteral("\">Download a PDF receipt</a> for this transaction.\r\n</p>\r\n\r\n<p class=\"last\">\r\n   " +
" Thanks for your business!\r\n</p>\r\n");


        }
    }
}
#pragma warning restore 1591
